# Generated by Django 5.1.1 on 2024-11-02 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Extra', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
