# Generated by Django 5.1.1 on 2024-11-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Extra', '0002_rename_reviews_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Age',
            new_name='Exp',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='Email',
            new_name='Future',
        ),
        migrations.AddField(
            model_name='review',
            name='Rev',
            field=models.CharField(default='default review', max_length=120),
            preserve_default=False,
        ),
    ]
